---------------------------------------------------
---------------------- 함수 ------------------------
---------------------------------------------------
CREATE OR REPLACE FUNCTION FN_GET_BOARD_ATTACHMENT_SEQ_NEXTVAL
    RETURN NUMBER
IS 
    X NUMBER; 
BEGIN 
    SELECT  SEQ_BOARD_ATTACHMENT.NEXTVAL
    INTO    X
    FROM    DUAL;
    
    RETURN X; 
END
;
/

---------------------------------------------------
---------------------- 삭제 ------------------------
---------------------------------------------------
DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_ADMIN;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_BOARD_ATTACHMENT;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_BOARD_REPLY;
DROP SEQUENCE SEQ_CATEGORY;

DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE BOARD_ATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE BOARD_REPLY CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;

---------------------------------------------------
--------------------- 시퀀스 -----------------------
---------------------------------------------------
CREATE SEQUENCE SEQ_MEMBER              NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADMIN               NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD               NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD_ATTACHMENT    NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE              NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD_REPLY         NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORY            NOCACHE NOCYCLE;

---------------------------------------------------
--------------------- 테이블 -----------------------
---------------------------------------------------
CREATE TABLE MEMBER(
    NO              NUMBER          PRIMARY KEY
    , ID            VARCHAR2(100)   NOT NULL UNIQUE
    , PWD           VARCHAR2(100)   NOT NULL
    , NICK          VARCHAR2(100)   NOT NULL UNIQUE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE   TIMESTAMP 
    , PROFILE       VARCHAR2(255)
);

CREATE TABLE ADMIN(
    NO          NUMBER          PRIMARY KEY
    , ID        VARCHAR2(100)   NOT NULL UNIQUE
    , PWD       VARCHAR2(100)   NOT NULL
    , NICK      VARCHAR2(100)   NOT NULL UNIQUE
    , DEL_YN    CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE BOARD(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(1000)  NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , CATEGORY_NO   NUMBER          
    , WRITER_NO     NUMBER          NOT NULL
    , HIT           NUMBER          DEFAULT 0
    , CREATE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE BOARD_ATTACHMENT(
    NO              NUMBER          PRIMARY KEY
    , REF_NO        NUMBER          NOT NULL
    , ORIGIN_NAME   VARCHAR2(255)   
    , CHANGE_NAME   VARCHAR2(255)   NOT NULL UNIQUE
    , UPLOAD_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N'
);

CREATE TABLE NOTICE(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(1000)  NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , WRITER_NO     NUMBER          NOT NULL
    , HIT           NUMBER          DEFAULT 0
    , CREATE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE BOARD_REPLY(
    NO              NUMBER          PRIMARY KEY
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , REF_NO        NUMBER          NOT NULL
    , WRITER_NO     NUMBER          NOT NULL
    , CREATE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE CATEGORY(
    NO              NUMBER          PRIMARY KEY
    , NAME          VARCHAR2(30)    NOT NULL UNIQUE
);



---------------------------------------------------
--------------------- 외래키 -----------------------
---------------------------------------------------
ALTER TABLE NOTICE ADD CONSTRAINT FK_NOTICE_BOARD FOREIGN KEY (WRITER_NO) REFERENCES ADMIN(NO);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_CATEGORY FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(NO);
ALTER TABLE BOARD_ATTACHMENT ADD CONSTRAINT FK_BOARD_ATTACHMENT_BOARD FOREIGN KEY (REF_NO) REFERENCES BOARD(NO);
ALTER TABLE BOARD_REPLY ADD CONSTRAINT FK_BOARD_REPLY_BOARD FOREIGN KEY (REF_NO) REFERENCES BOARD(NO);
ALTER TABLE BOARD_REPLY ADD CONSTRAINT FK_BOARD_REPLY_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);

---------------------------------------------------
--------------------- 데이터 -----------------------
---------------------------------------------------
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'master' , '1234', '마스터');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin' , '1234', '운영자');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin01' , '1234', '운영자1');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin02' , '1234', '운영자2');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin031' , '1234', '운영자3');
COMMIT;

INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '자유');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '운동');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '게임');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '개발');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '자바');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '코딩');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '낚시');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '요리');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '댄스');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '기타');
COMMIT;

INSERT INTO MEMBER(NO, ID, PWD, NICK) VALUES(0 , 'user00', '1234', 'nick00');
COMMIT;

INSERT INTO BOARD(NO, TITLE, CONTENT, CATEGORY_NO, WRITER_NO) VALUES(SEQ_BOARD.NEXTVAL, '제목ㅋㅋㅋ', '내용ㅋㅋㅋ', 1, 0);
INSERT INTO BOARD(NO, TITLE, CONTENT, CATEGORY_NO, WRITER_NO) VALUES(SEQ_BOARD.NEXTVAL, '제목ㅋㅋㅋ', '내용ㅋㅋㅋ', 1, 0);
INSERT INTO BOARD(NO, TITLE, CONTENT, CATEGORY_NO, WRITER_NO) VALUES(SEQ_BOARD.NEXTVAL, '제목ㅋㅋㅋ', '내용ㅋㅋㅋ', 1, 0);
INSERT INTO BOARD(NO, TITLE, CONTENT, CATEGORY_NO, WRITER_NO) VALUES(SEQ_BOARD.NEXTVAL, '제목ㅋㅋㅋ', '내용ㅋㅋㅋ', 1, 0);
INSERT INTO BOARD(NO, TITLE, CONTENT, CATEGORY_NO, WRITER_NO) VALUES(SEQ_BOARD.NEXTVAL, '제목ㅋㅋㅋ', '내용ㅋㅋㅋ', 1, 0);
COMMIT;

INSERT INTO BOARD_REPLY ( NO ,CONTENT ,REF_NO ,WRITER_NO ) VALUES ( SEQ_BOARD_REPLY.NEXTVAL , 'hello~' , 1 , 0 );
INSERT INTO BOARD_REPLY ( NO ,CONTENT ,REF_NO ,WRITER_NO ) VALUES ( SEQ_BOARD_REPLY.NEXTVAL , 'world' , 1 , 0 );
INSERT INTO BOARD_REPLY ( NO ,CONTENT ,REF_NO ,WRITER_NO ) VALUES ( SEQ_BOARD_REPLY.NEXTVAL , 'bye' , 1 , 0 );
COMMIT;
























