--------------------------------
---------- 시퀀스 삭제-----------
--------------------------------
DROP SEQUENCE SEQ_ORDER_SHEET_NO;
DROP SEQUENCE SEQ_MEMBER_ADMIN_NO;
DROP SEQUENCE SEQ_MEMBER_STORE_OWNER_NO;
DROP SEQUENCE SEQ_STAMP_NO;
DROP SEQUENCE SEQ_FOOD_INFOR_NO;
DROP SEQUENCE SEQ_STORE_INFOR_NO;
DROP SEQUENCE SEQ_MEMBER_USER_NO;
DROP SEQUENCE SEQ_REVIEW_COMMUNICATION_NO;
DROP SEQUENCE SEQ_ROCAL_NAME_NO;
DROP SEQUENCE SEQ_ORDER_DETAIL_NO;
DROP SEQUENCE SEQ_ORDER_STATUS_NO;
DROP SEQUENCE SEQ_FOOD_MENU_CATEGORY_NO;
DROP SEQUENCE SEQ_APPROVAL_STATUS_NO;
DROP SEQUENCE SEQ_STORE_CATEGORY_NO;
DROP SEQUENCE SEQ_CLOSED_DAY_NO;
DROP SEQUENCE SEQ_FOOD_IMAGE_NO;
DROP SEQUENCE SEQ_CART_NO;
DROP SEQUENCE SEQ_DELIVERY_ZONE_NO;
DROP SEQUENCE SEQ_DELIVERY_PROBLEM_NO;
DROP SEQUENCE SEQ_GENERATION_NO;

--------------------------------
---------- 시퀀스 생성 ----------
--------------------------------

CREATE SEQUENCE SEQ_ORDER_SHEET_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MEMBER_ADMIN_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MEMBER_STORE_OWNER_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_STAMP_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FOOD_INFOR_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_STORE_INFOR_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MEMBER_USER_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REVIEW_COMMUNICATION_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ROCAL_NAME_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDER_DETAIL_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDER_STATUS_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FOOD_MENU_CATEGORY_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_APPROVAL_STATUS_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_STORE_CATEGORY_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CLOSED_DAY_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FOOD_IMAGE_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CART_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DELIVERY_ZONE_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DELIVERY_PROBLEM_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_GENERATION_NO NOCACHE NOCYCLE;

------------------------------------------------------
-------------------- 테이블 제거 ----------------------
------------------------------------------------------
DROP TABLE STORE_DELIVERY_ZONE CASCADE CONSTRAINTS;
DROP TABLE LOCAL_NAME CASCADE CONSTRAINTS;
DROP TABLE DELIVERY_ZONE CASCADE CONSTRAINTS;
DROP TABLE CLOSED_DAY CASCADE CONSTRAINTS;
DROP TABLE STORE_INFOR CASCADE CONSTRAINTS;
DROP TABLE MEMBER_STORE_OWNER CASCADE CONSTRAINTS;
DROP TABLE STORE_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE APPROVAL_STATUS CASCADE CONSTRAINTS;
DROP TABLE FOOD_IMG CASCADE CONSTRAINTS;
DROP TABLE FOOD_INFOR CASCADE CONSTRAINTS;
DROP TABLE MEMBER_ADMIN CASCADE CONSTRAINTS;
DROP TABLE DELIVERY_PROBLEM CASCADE CONSTRAINTS;
DROP TABLE MEMBER_USER CASCADE CONSTRAINTS;
DROP TABLE GENERATION CASCADE CONSTRAINTS;
DROP TABLE STAMP CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE ORDER_DETAIL CASCADE CONSTRAINTS;
DROP TABLE ORDER_SHEET CASCADE CONSTRAINTS;
DROP TABLE REVIEW_COMMUNICATION CASCADE CONSTRAINTS;
DROP TABLE ORDER_STATUS CASCADE CONSTRAINTS;
DROP TABLE FOOD_MENU_CATEGORY CASCADE CONSTRAINTS;


-----------------------------------------------------
--------------------- 테이블생성 ---------------------
-----------------------------------------------------
-- 음식 메뉴 카테고리 FOOD_MENU_CATEGORY 참조X
CREATE TABLE FOOD_MENU_CATEGORY (
    NO       NUMBER       PRIMARY KEY,
    NAME     VARCHAR2(60) NOT NULL,
    VIEW_YN  CHAR(1)      NOT NULL CHECK (VIEW_YN IN ('Y','N'))
);


-- 배달구역 테이블은 참조하는 테이블 없음
CREATE TABLE DELIVERY_ZONE (
    NO          NUMBER      PRIMARY KEY
);

-- 배달지역이름 테이블은 DELIVERY_ZONE 테이블 참조
CREATE TABLE LOCAL_NAME (
    NO              NUMBER          PRIMARY KEY,
    ZONE_NUMBER     NUMBER          NOT NULL,
    ADDRESS         VARCHAR2(50)    NOT NULL
);

-- 업종분류 테이블은 참조하는 테이블 없음
CREATE TABLE STORE_CATEGORY (
    NO       NUMBER       PRIMARY KEY,
    NAME     VARCHAR2(20) NOT NULL
);

-- 휴무 테이블은 가게정보테이블을 참조함
CREATE TABLE CLOSED_DAY (
    NO           NUMBER        PRIMARY KEY,
    DAY          DATE          NOT NULL,
    "COMMENT"      VARCHAR2(100) NOT NULL,
    STORE_NO     NUMBER        NOT NULL
);

-- 가게정보테이블
CREATE TABLE STORE_INFOR (
    NO                               NUMBER            PRIMARY KEY,
    NAME                             VARCHAR2(20)      NOT NULL,
    ADDRESS                          VARCHAR2(60)      NOT NULL,
    ADDRESS_DETAIL                   VARCHAR2(60)      NOT NULL,
    BUSINESS_REGISTRATION_CERTIFICATE_IMG VARCHAR2(1000),
    INTRODUCTION_IMG                 VARCHAR2(1000),
    INTRODUCE                        VARCHAR2(50),
    MAIN_IMG                         VARCHAR2(1000)    NOT NULL,
    PHONE                            CHAR(14),
    MINIMUM_ORDER_AMOUNT             NUMBER,
    VIEWED_CNT                       NUMBER,
    OPEN_TIME                        DATE              NOT NULL,
    END_TIME                         DATE              NOT NULL,
    BREAK_TIME_START                 DATE,
    BREAK_TIME_END                   DATE,
    STORE_OWNER_NO                   NUMBER            NOT NULL,
    STORE_CATEGORY_NO                NUMBER            NOT NULL,
    APPROVAL_STATUS_NO               NUMBER            NOT NULL
);

-- 가게배달구역 테이블: STORE_INFOR 가게정보 테이블 참조, DELIVERY_ZONE 배달구역 테이블 참조
CREATE TABLE STORE_DELIVERY_ZONE (
    ZONE_NO NUMBER,
    STORE_NO NUMBER
);

-- 사장계정 테이블은 참조하는 테이블 없음
CREATE TABLE MEMBER_STORE_OWNER (
    NO                          NUMBER        PRIMARY KEY,
    ID                          VARCHAR2(10)  NOT NULL UNIQUE,
    PWD                         VARCHAR2(10)  NOT NULL,
    NAME                        VARCHAR2(30)  NOT NULL,
    PHONE                       CHAR(15)      NOT NULL,
    DEL_YN                      CHAR(1)       DEFAULT 'N' CHECK (DEL_YN IN ('Y','N')),
    COMPANY_RESITRATION_NUMBER   CHAR(12)      NOT NULL UNIQUE,
    PROFILE                     VARCHAR2(1000) NOT NULL
);

-- 가게승인상태 테이블은 참조하는 테이블 없음
CREATE TABLE APPROVAL_STATUS (
    NO       NUMBER       PRIMARY KEY,
    STATUS   VARCHAR2(10) NOT NULL
);

-- 음식정보테이블은 음식 메뉴 카테고리 테이블 FOOD_MENU_CATEGORY 참조
CREATE TABLE FOOD_INFOR (
    NO                     NUMBER          PRIMARY KEY,
    NAME                   VARCHAR2(30)    NOT NULL,
    PRICE                  NUMBER          NOT NULL,
    FOOD_MENU_CATEGORY_NO  NUMBER          NOT NULL,
    VIEW_YN                CHAR(1)         NOT NULL CHECK (VIEW_YN IN ('Y','N')),
    STORE_NO               NUMBER          NOT NULL
);

-- 음식사진 테이블은 음식정보 FOOD_INFOR 참조
CREATE TABLE FOOD_IMG (
    NO        NUMBER       PRIMARY KEY,
    IMG_NAME  VARCHAR2(1000)  NOT NULL,
    DEL_YN    CHAR(1)       DEFAULT 'N' CHECK (DEL_YN IN ('Y','N')),
    FOOD_NO   NUMBER       NOT NULL
);



-------------관리자 계정---------


CREATE TABLE MEMBER_ADMIN (
    NO          NUMBER          PRIMARY KEY,
    ID          VARCHAR2(10)    NOT NULL,
    PWD         VARCHAR2(10)    NOT NULL,
    DEL_YN      CHAR(1) DEFAULT 'N'  NOT NULL -- DEFAULT와 NOT NULL 위치 변경
);
-----------배달 문제 선택---------

CREATE TABLE DELIVERY_PROBLEM (
    NO                  NUMBER      PRIMARY KEY,
    DELIVERY_PROBLEM    VARCHAR2(30) NOT NULL
);

------------------회원 정보-------------------

CREATE TABLE MEMBER_USER (
    NO               NUMBER                 PRIMARY KEY,
    NICK             VARCHAR2(30)           NOT NULL,
    ID               VARCHAR2(10)           NOT NULL UNIQUE,
    PWD              VARCHAR2(10)           NOT NULL,
    NAME             VARCHAR2(30)           NOT NULL,
    ADDRESS          VARCHAR2(60)           NOT NULL,
    ADDRESS_DETAIL   VARCHAR2(60)           NOT NULL,
    PHONE            CHAR(14)               NOT NULL,
    ACCOUNT_BALANCE  NUMBER                 NOT NULL,
    DEL_YN           CHAR(1)                DEFAULT 'N' CHECK(DEL_YN IN ('Y','N')) NOT NULL, 
    GENDER           CHAR(1)                NOT NULL,
    PROFILE          VARCHAR2(30)           NOT NULL,
    GENERATION       NUMBER                 NOT NULL 
 
);
-----------세대---------------

CREATE TABLE GENERATION (
    NO          NUMBER          PRIMARY KEY,
    GENERATION  VARCHAR2(30)    NOT NULL
);

------------스탬프------------


CREATE TABLE STAMP (
    NO               NUMBER      PRIMARY KEY,
    STORE_NO         NUMBER       NOT NULL,
    MEMBER_USER_NO   NUMBER      NOT NULL
 
);

--------------장바구니----------

CREATE TABLE CART (
    NO          NUMBER      PRIMARY KEY,
    USER_NO     NUMBER      NOT NULL,
    FOOD_COUNT  NUMBER      NOT NULL,
    FOOD_NO     NUMBER      NOT NULL
 
);
---------------주문--------------

CREATE TABLE ORDER_SHEET (
    NO               NUMBER          PRIMARY KEY,
    REQUEST_MSG     VARCHAR2(50)        NULL ,
    TOTAL_ORDER_PAY NUMBER              NOT NULL,
    ORDER_DAY       DATE              DEFAULT SYSDATE NOT NULL,
    ADDRESS         VARCHAR2(50)        NOT NULL,
    STORE_NO         NUMBER             NOT NULL,
    USER_NO         NUMBER              NOT NULL,
    STATUS_NO       NUMBER              NOT NULL,
    DELIVERY_PROBLEM NUMBER             NULL

);

---------------------리뷰_의사소통---------

CREATE TABLE REVIEW_COMMUNICATION (
    NO               NUMBER         PRIMARY KEY,
    ORDER_NO         NUMBER         NOT NULL,
    RATING           NUMBER         NOT NULL,
    USER_CONTENT     VARCHAR2(50)   NULL,
    STORE_CONTENT   VARCHAR2(50)    NULL,
    IMG             VARCHAR2(200)   NULL,
    ENROLL_DATE     TIMESTAMP DEFAULT SYSDATE,
    DEL_YN CHAR(1)  DEFAULT 'N' CHECK(DEL_YN IN ('Y','N')) NOT NULL
    
   
);
------------주문 상세----------

CREATE TABLE ORDER_DETAIL (
    NO           NUMBER     PRIMARY KEY,
    FOOD_COUNT   NUMBER     NOT NULL,
    FOOD_PRICE   NUMBER     NOT NULL,
    ORDER_NO     NUMBER     NOT NULL,
    FOOD_NO      NUMBER     NOT NULL
    

);
---------------주문 상태------------

CREATE TABLE ORDER_STATUS (
    NO      NUMBER          PRIMARY KEY,
    STATUS  VARCHAR2(15)    NOT NULL
);





-- 가게배달구역 테이블=
-- 2. 기본 키 제약 조건 추가
ALTER TABLE STORE_DELIVERY_ZONE
ADD CONSTRAINT PK_STORE_DELIVERY_ZONE PRIMARY KEY (ZONE_NO, STORE_NO);

-- 3. 외래 키 제약 조건 추가
ALTER TABLE STORE_DELIVERY_ZONE
ADD CONSTRAINT FK_STORE_DELIVERY_ZONE_STORE_INFOR
FOREIGN KEY (STORE_NO) REFERENCES STORE_INFOR (NO);

ALTER TABLE STORE_DELIVERY_ZONE
ADD CONSTRAINT FK_STORE_DELIVERY_ZONE_DELIVERY_ZONE
FOREIGN KEY (ZONE_NO) REFERENCES DELIVERY_ZONE (NO);
-- 배달지역이름 테이블
ALTER TABLE LOCAL_NAME
    ADD CONSTRAINT FK_LOCAL_NAME_DELIVERY_ZONE FOREIGN KEY (ZONE_NUMBER) REFERENCES DELIVERY_ZONE(NO);

-- 휴무 테이블
ALTER TABLE CLOSED_DAY
    ADD CONSTRAINT FK_CLOSED_DAY_STORE_INFOR FOREIGN KEY (STORE_NO) REFERENCES STORE_INFOR(NO);

-- 가게정보테이블
ALTER TABLE STORE_INFOR
    ADD CONSTRAINT FK_STORE_MEMBER_STORE_OWNER FOREIGN KEY (STORE_OWNER_NO) REFERENCES MEMBER_STORE_OWNER(NO);

ALTER TABLE STORE_INFOR
    ADD CONSTRAINT FK_STORE_INFOR_STORE_CATEGORY FOREIGN KEY (STORE_CATEGORY_NO) REFERENCES STORE_CATEGORY(NO);

ALTER TABLE STORE_INFOR
    ADD CONSTRAINT FK_STORE_INFOR_APPROVAL_STATUS FOREIGN KEY (APPROVAL_STATUS_NO) REFERENCES APPROVAL_STATUS(NO);

-- 음식정보테이블
ALTER TABLE FOOD_INFOR
    ADD CONSTRAINT FK_FOOD_INFOR_STORE_INFOR FOREIGN KEY (STORE_NO) REFERENCES STORE_INFOR(NO);

ALTER TABLE FOOD_INFOR
    ADD CONSTRAINT FK_FOOD_INFOR_FOOD_MENU_CATEGORY FOREIGN KEY (FOOD_MENU_CATEGORY_NO) REFERENCES FOOD_MENU_CATEGORY(NO);

-- 음식사진 테이블
ALTER TABLE FOOD_IMG
    ADD CONSTRAINT FK_FOOD_IMAGE_FOOD_INFOR FOREIGN KEY (FOOD_NO) REFERENCES FOOD_INFOR(NO);


 ------회원정보
 
 ALTER TABLE MEMBER_USER ADD CONSTRAINT FK_MEMBER_USER_TO_GENERATION FOREIGN KEY (GENERATION) REFERENCES GENERATION (NO);

----주문 상세

 
 ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_ORDER_DETAIL_TO_FOOD_INFOR FOREIGN KEY (FOOD_NO) REFERENCES FOOD_INFOR (NO);

ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_ORDER_DETAIL_TO_ODER_SHEET FOREIGN KEY (ORDER_NO) REFERENCES ORDER_SHEET (NO);

 
---리뷰 커뮤니
ALTER TABLE REVIEW_COMMUNICATION ADD CONSTRAINT FK_REVIEW_COMMUNICATION_TO_ORDER_SHEET FOREIGN KEY (ORDER_NO) REFERENCES ORDER_SHEET (NO);

---스탬프
ALTER TABLE STAMP ADD CONSTRAINT FK_STAMP_TO_STORE_INFOR FOREIGN KEY (STORE_NO) REFERENCES STORE_INFOR (NO);

ALTER TABLE STAMP ADD CONSTRAINT FK_STAMP_TO_MEMBER_USER FOREIGN KEY (MEMBER_USER_NO) REFERENCES MEMBER_USER (NO);

----장바구니
ALTER TABLE CART ADD CONSTRAINT FK_CART_TO_FOOD_INFOR FOREIGN KEY (FOOD_NO) REFERENCES FOOD_INFOR (NO);

ALTER TABLE CART ADD CONSTRAINT FK_CART_TO_MEMBER_USER FOREIGN KEY (USER_NO) REFERENCES MEMBER_USER (NO);

---- 주문
ALTER TABLE ORDER_SHEET ADD CONSTRAINT FK_ORDER_SHEET_TO_STORE_INFOR FOREIGN KEY (STORE_NO) REFERENCES STORE_INFOR (NO);

ALTER TABLE ORDER_SHEET ADD CONSTRAINT FK_ORDER_SHEET_TO_MEMBER_USER FOREIGN KEY (USER_NO) REFERENCES MEMBER_USER (NO);

ALTER TABLE ORDER_SHEET ADD CONSTRAINT FK_ORDER_SHEET_TO_ORDER_STATUS FOREIGN KEY (STATUS_NO) REFERENCES ORDER_STATUS (NO);

ALTER TABLE ORDER_SHEET ADD CONSTRAINT FK_ORDER_SHEET_TO_DELIVERY_PROBLEM FOREIGN KEY (DELIVERY_PROBLEM) REFERENCES DELIVERY_PROBLEM (NO);


COMMIT; 