--사용자 계정 생성

-- CREATE USER 계정명 IDENTIFIED BY 비밀번호;
CREATE USER C##KH_PRACTICE IDENTIFIED BY 1234;

-- 권한부여
-- GRANT 권한1, 권한2 , ... TO 계정명;
GRANT RESOURCE, CONNECT TO C##KH_PRACTICE;

-- 테이블 스페이스 (ORA-01950)
ALTER USER C##KH_PRACTICE DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;